Add server properties generation logic

diff --git a/docker/resources/common-scripts/configure b/docker/resources/common-scripts/configure
--- a/docker/resources/common-scripts/configure
+++ b/docker/resources/common-scripts/configure
@@ -120,32 +120,45 @@ then
   fi
 fi
 
-# Copy the bundled log4j.properties and tools-log4j.properties. This is done to handle property modification during container restart
+
+###############################
+
 cp /etc/kafka/docker/log4j.properties /opt/kafka/config/log4j.properties
 cp /etc/kafka/docker/tools-log4j.properties /opt/kafka/config/tools-log4j.properties
 
-# Copy all the user provided property files through file input
+# Ensure the current server.properties file is deleted
+if [ -e "/opt/kafka/config/server.properties" ]; then
+  rm /opt/kafka/config/server.properties
+fi
+
 cp -R /mnt/shared/config/. /opt/kafka/config/
 
-# Check the presence of user provided kafka configs via file input
-if [ -e "/mnt/shared/config/server.properties" ]
-then
-  echo "User provided kafka configs found via file input. Any properties provided via env variables will be appended to this."
-  # Append configs provided via env variables.
-  echo -e "\n$(utility render-properties /etc/kafka/docker/kafka-propertiesSpec.json)" >> /opt/kafka/config/server.properties
-else
-  # Create the kafka config property file using user provided environment variables.
-  echo -e "\n$(utility render-properties /etc/kafka/docker/kafka-propertiesSpec.json)" > /opt/kafka/config/server.properties
-  if grep -q '[^[:space:]]' "/opt/kafka/config/server.properties"; then
-    echo "User provided kafka configs found via environment variables."
-  fi
-fi
-
-# If no user provided kafka configs found, use default configs
-if ! grep -q '[^[:space:]]' "/opt/kafka/config/server.properties"; then
-  echo "User provided kafka configs not found (neither via file input nor via environment variables). Falling back to default configs."
-  cp /etc/kafka/docker/server.properties /opt/kafka/config/server.properties
-fi
-
-echo -e "\n$(utility render-template /etc/kafka/docker/kafka-log4j.properties.template)" >> /opt/kafka/config/log4j.properties
-echo -e "\n$(utility render-template /etc/kafka/docker/kafka-tools-log4j.properties.template)" >> /opt/kafka/config/tools-log4j.properties
+## Copy the bundled log4j.properties and tools-log4j.properties. This is done to handle property modification during container restart
+#cp /etc/kafka/docker/log4j.properties /opt/kafka/config/log4j.properties
+#cp /etc/kafka/docker/tools-log4j.properties /opt/kafka/config/tools-log4j.properties
+#
+## Copy all the user provided property files through file input
+#cp -R /mnt/shared/config/. /opt/kafka/config/
+#
+## Check the presence of user provided kafka configs via file input
+#if [ -e "/mnt/shared/config/server.properties" ]
+#then
+#  echo "User provided kafka configs found via file input. Any properties provided via env variables will be appended to this."
+#  # Append configs provided via env variables.
+#  echo -e "\n$(utility render-properties /etc/kafka/docker/kafka-propertiesSpec.json)" >> /opt/kafka/config/server.properties
+#else
+#  # Create the kafka config property file using user provided environment variables.
+#  echo -e "\n$(utility render-properties /etc/kafka/docker/kafka-propertiesSpec.json)" > /opt/kafka/config/server.properties
+#  if grep -q '[^[:space:]]' "/opt/kafka/config/server.properties"; then
+#    echo "User provided kafka configs found via environment variables."
+#  fi
+#fi
+#
+## If no user provided kafka configs found, use default configs
+#if ! grep -q '[^[:space:]]' "/opt/kafka/config/server.properties"; then
+#  echo "User provided kafka configs not found (neither via file input nor via environment variables). Falling back to default configs."
+#  cp /etc/kafka/docker/server.properties /opt/kafka/config/server.properties
+#fi
+#
+#echo -e "\n$(utility render-template /etc/kafka/docker/kafka-log4j.properties.template)" >> /opt/kafka/config/log4j.properties
+#echo -e "\n$(utility render-template /etc/kafka/docker/kafka-tools-log4j.properties.template)" >> /opt/kafka/config/tools-log4j.properties
