Merge branch 'trunk' into native-docker-image

diff --git a/docker/resources/common-scripts/configure b/docker/resources/common-scripts/configure
--- a/docker/resources/common-scripts/configure
+++ b/docker/resources/common-scripts/configure
@@ -14,15 +14,11 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# --- for broker
-
-# If KAFKA_PROCESS_ROLES is defined it means we are running in KRaft mode
-
 # unset KAFKA_ADVERTISED_LISTENERS from ENV in KRaft mode when running as controller only
 if [[ -n "${KAFKA_PROCESS_ROLES-}" ]]
 then
   echo "Running in KRaft mode..."
-  ub ensure CLUSTER_ID
+  utility ensure CLUSTER_ID
   if [[ $KAFKA_PROCESS_ROLES == "controller" ]]
   then
     if [[ -n "${KAFKA_ADVERTISED_LISTENERS-}" ]]
@@ -30,11 +26,10 @@ then
       echo "KAFKA_ADVERTISED_LISTENERS is not supported on a KRaft controller."
       exit 1
     else
+      # Unset in case env variable is set with empty value
       unset KAFKA_ADVERTISED_LISTENERS
     fi
-  else
-    ub ensure KAFKA_ADVERTISED_LISTENERS
-  fi 
+  fi
 fi
 
 # By default, LISTENERS is derived from ADVERTISED_LISTENERS by replacing
@@ -46,67 +41,41 @@ then
   KAFKA_LISTENERS=$(echo "$KAFKA_ADVERTISED_LISTENERS" | sed -e 's|://[^:]*:|://0.0.0.0:|g')
 fi
 
-ub path /opt/kafka/config/ writable
-
-# advertised.host, advertised.port, host and port are deprecated. Exit if these properties are set.
-if [[ -n "${KAFKA_ADVERTISED_PORT-}" ]]
-then
-  echo "advertised.port is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead."
-  exit 1
-fi
-
-if [[ -n "${KAFKA_ADVERTISED_HOST-}" ]]
-then
-  echo "advertised.host is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead."
-  exit 1
-fi
-
-if [[ -n "${KAFKA_HOST-}" ]]
-then
-  echo "host is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead."
-  exit 1
-fi
-
-if [[ -n "${KAFKA_PORT-}" ]]
-then
-  echo "port is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead."
-  exit 1
-fi
+utility path /opt/kafka/config/ writable
 
 # Set if ADVERTISED_LISTENERS has SSL:// or SASL_SSL:// endpoints.
 if [[ -n "${KAFKA_ADVERTISED_LISTENERS-}" ]] && [[ $KAFKA_ADVERTISED_LISTENERS == *"SSL://"* ]]
 then
   echo "SSL is enabled."
 
-  ub ensure KAFKA_SSL_KEYSTORE_FILENAME
+  utility ensure KAFKA_SSL_KEYSTORE_FILENAME
   export KAFKA_SSL_KEYSTORE_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_KEYSTORE_FILENAME"
-  ub path "$KAFKA_SSL_KEYSTORE_LOCATION" existence
+  utility path "$KAFKA_SSL_KEYSTORE_LOCATION" existence
 
-  ub ensure KAFKA_SSL_KEY_CREDENTIALS
+  utility ensure KAFKA_SSL_KEY_CREDENTIALS
   KAFKA_SSL_KEY_CREDENTIALS_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_KEY_CREDENTIALS"
-  ub path "$KAFKA_SSL_KEY_CREDENTIALS_LOCATION" existence
+  utility path "$KAFKA_SSL_KEY_CREDENTIALS_LOCATION" existence
   export KAFKA_SSL_KEY_PASSWORD
   KAFKA_SSL_KEY_PASSWORD=$(cat "$KAFKA_SSL_KEY_CREDENTIALS_LOCATION")
 
-  ub ensure KAFKA_SSL_KEYSTORE_CREDENTIALS
+  utility ensure KAFKA_SSL_KEYSTORE_CREDENTIALS
   KAFKA_SSL_KEYSTORE_CREDENTIALS_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_KEYSTORE_CREDENTIALS"
-  ub path "$KAFKA_SSL_KEYSTORE_CREDENTIALS_LOCATION" existence
+  utility path "$KAFKA_SSL_KEYSTORE_CREDENTIALS_LOCATION" existence
   export KAFKA_SSL_KEYSTORE_PASSWORD
   KAFKA_SSL_KEYSTORE_PASSWORD=$(cat "$KAFKA_SSL_KEYSTORE_CREDENTIALS_LOCATION")
 
   if [[ -n "${KAFKA_SSL_CLIENT_AUTH-}" ]] && ( [[ $KAFKA_SSL_CLIENT_AUTH == *"required"* ]] || [[ $KAFKA_SSL_CLIENT_AUTH == *"requested"* ]] )
   then
-      ub ensure KAFKA_SSL_TRUSTSTORE_FILENAME
+      utility ensure KAFKA_SSL_TRUSTSTORE_FILENAME
       export KAFKA_SSL_TRUSTSTORE_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_TRUSTSTORE_FILENAME"
-      ub path "$KAFKA_SSL_TRUSTSTORE_LOCATION" existence
+      utility path "$KAFKA_SSL_TRUSTSTORE_LOCATION" existence
 
-      ub ensure KAFKA_SSL_TRUSTSTORE_CREDENTIALS
+      utility ensure KAFKA_SSL_TRUSTSTORE_CREDENTIALS
       KAFKA_SSL_TRUSTSTORE_CREDENTIALS_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_TRUSTSTORE_CREDENTIALS"
-      ub path "$KAFKA_SSL_TRUSTSTORE_CREDENTIALS_LOCATION" existence
+      utility path "$KAFKA_SSL_TRUSTSTORE_CREDENTIALS_LOCATION" existence
       export KAFKA_SSL_TRUSTSTORE_PASSWORD
       KAFKA_SSL_TRUSTSTORE_PASSWORD=$(cat "$KAFKA_SSL_TRUSTSTORE_CREDENTIALS_LOCATION")
   fi
-  
 fi
 
 # Set if KAFKA_ADVERTISED_LISTENERS has SASL_PLAINTEXT:// or SASL_SSL:// endpoints.
@@ -114,7 +83,7 @@ if [[ -n "${KAFKA_ADVERTISED_LISTENERS-}" ]] && [[ $KAFKA_ADVERTISED_LISTENERS =
 then
   echo "SASL" is enabled.
 
-  ub ensure KAFKA_OPTS
+  utility ensure KAFKA_OPTS
 
   if [[ ! $KAFKA_OPTS == *"java.security.auth.login.config"*  ]]
   then
@@ -130,12 +99,32 @@ then
   fi
 fi
 
-mv /etc/kafka/docker/server.properties /opt/kafka/config/server.properties
-mv /etc/kafka/docker/log4j.properties /opt/kafka/config/log4j.properties
-mv /etc/kafka/docker/tools-log4j.properties /opt/kafka/config/tools-log4j.properties
+# Copy the bundled log4j.properties and tools-log4j.properties. This is done to handle property modification during container restart
+cp /etc/kafka/docker/log4j.properties /opt/kafka/config/log4j.properties
+cp /etc/kafka/docker/tools-log4j.properties /opt/kafka/config/tools-log4j.properties
 
+# Copy all the user provided property files through file input
 cp -R /mnt/shared/config/. /opt/kafka/config/
 
-echo -e "\n$(ub render-properties /etc/kafka/docker/kafka-propertiesSpec.json)" >> /opt/kafka/config/server.properties
-echo -e "\n$(ub render-template /etc/kafka/docker/kafka-log4j.properties.template)" >> /opt/kafka/config/log4j.properties
-echo -e "\n$(ub render-template /etc/kafka/docker/kafka-tools-log4j.properties.template)" >> /opt/kafka/config/tools-log4j.properties
+# Check the presence of user provided kafka configs via file input
+if [ -e "/mnt/shared/config/server.properties" ]
+then
+  echo "User provided kafka configs found via file input. Any properties provided via env variables will be appended to this."
+  # Append configs provided via env variables.
+  echo -e "\n$(utility render-properties /etc/kafka/docker/kafka-propertiesSpec.json)" >> /opt/kafka/config/server.properties
+else
+  # Create the kafka config property file using user provided environment variables.
+  echo -e "\n$(utility render-properties /etc/kafka/docker/kafka-propertiesSpec.json)" > /opt/kafka/config/server.properties
+  if grep -q '[^[:space:]]' "/opt/kafka/config/server.properties"; then
+    echo "User provided kafka configs found via environment variables."
+  fi
+fi
+
+# If no user provided kafka configs found, use default configs
+if ! grep -q '[^[:space:]]' "/opt/kafka/config/server.properties"; then
+  echo "User provided kafka configs not found (neither via file input nor via environment variables). Falling back to default configs."
+  cp /opt/kafka/config/kraft/server.properties /opt/kafka/config/server.properties
+fi
+
+echo -e "\n$(utility render-template /etc/kafka/docker/kafka-log4j.properties.template)" >> /opt/kafka/config/log4j.properties
+echo -e "\n$(utility render-template /etc/kafka/docker/kafka-tools-log4j.properties.template)" >> /opt/kafka/config/tools-log4j.properties
