Make ci-complete support 4.0 buildscan

diff --git a/.github/workflows/ci-complete.yml b/.github/workflows/ci-complete.yml
--- a/.github/workflows/ci-complete.yml
+++ b/.github/workflows/ci-complete.yml
@@ -38,7 +38,10 @@ run-name: Build Scans for ${{ github.event.workflow_run.display_title}}
 jobs:
   upload-build-scan:
     # Skip this workflow if the CI run was skipped or cancelled
-    if: (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure')
+    if: >
+      (github.event.workflow_run.head_branch != '4.0') &&
+      (github.event.workflow_run.conclusion == 'success' || 
+       github.event.workflow_run.conclusion == 'failure')
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -89,7 +92,7 @@ jobs:
           url: '${{ github.event.workflow_run.html_url }}'
           description: 'Could not find build scan'
           context: Gradle Build Scan / ${{ env.status-context }}
-          state: 'success' # Always mark as successful as a temporary fix; non-trunk branches will miss build scan. Real fix in KAFKA-19768
+          state: 'error'
       - name: Publish Scan
         id: publish-build-scan
         if: ${{ steps.download-build-scan.outcome == 'success' }}
@@ -128,4 +131,93 @@ jobs:
           url: ${{ steps.publish-build-scan.outputs.build-scan-url }}
           description: 'The build scan was successfully published'
           context: Gradle Build Scan / ${{ env.status-context }}
+          state: 'success'
+
+  # All branches use the ci-complete workflow in the trunk branch,
+  # so the 4.0-specific logic must be maintained here in trunk.
+  upload-build-scan-4_0:
+    # Run for all branches except 4.0, and only if CI finished successfully or failed
+    if: >
+      (github.event.workflow_run.head_branch == '4.0') &&
+      (github.event.workflow_run.conclusion == 'success' ||
+       github.event.workflow_run.conclusion == 'failure')
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        java: [ 23, 17 ]
+        artifact-prefix: [ "build-scan-test-", "build-scan-quarantined-test-"]
+    steps:
+      - name: Env
+        run: printenv
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          persist-credentials:
+            false
+      - name: Setup Gradle
+        uses: ./.github/actions/setup-gradle
+        with:
+          java-version: ${{ matrix.java }}
+          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
+      - name: Download build scan archive
+        id: download-build-scan
+        uses: actions/download-artifact@v4
+        continue-on-error: true  # Don't want this step to fail the overall workflow
+        with:
+          github-token: ${{ github.token }}
+          run-id: ${{ github.event.workflow_run.id }}
+          name: ${{ matrix.artifact-prefix }}${{ matrix.java }}
+          path: ~/.gradle/build-scan-data  # This is where Gradle buffers unpublished build scan data when --no-scan is given
+      - name: Handle missing scan
+        if: ${{ steps.download-build-scan.outcome == 'failure' }}
+        uses: ./.github/actions/gh-api-update-status
+        with:
+          gh-token: ${{ secrets.GITHUB_TOKEN }}
+          repository: ${{ github.repository }}
+          commit_sha: ${{ github.event.workflow_run.head_sha }}
+          url: '${{ github.event.workflow_run.html_url }}'
+          description: 'Could not find build scan'
+          context: 'Gradle Build Scan / Java ${{ matrix.java }}'
+          state: 'error'
+      - name: Publish Scan
+        id: publish-build-scan
+        if: ${{ steps.download-build-scan.outcome == 'success' }}
+        run: |
+          set +e
+          ./gradlew --info buildScanPublishPrevious > gradle.out
+          exitcode="$?"
+          if [ $exitcode -ne 0 ]; then
+            cat gradle.out
+            echo "Failed to publish build scan" >> $GITHUB_STEP_SUMMARY
+            exit $exitcode
+          else
+            SCAN_URL=$(grep '^https://.*$' gradle.out)
+            cat gradle.out
+            echo "Published build scan to $SCAN_URL" >> $GITHUB_STEP_SUMMARY
+            echo "build-scan-url=$SCAN_URL" >> $GITHUB_OUTPUT
+          fi
+      - name: Handle failed publish
+        if: ${{ failure() && steps.publish-build-scan.outcome == 'failure' }}
+        uses: ./.github/actions/gh-api-update-status
+        with:
+          gh-token: ${{ secrets.GITHUB_TOKEN }}
+          repository: ${{ github.repository }}
+          commit_sha: ${{ github.event.workflow_run.head_sha }}
+          url: '${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}'
+          description: 'The build scan failed to be published'
+          context: 'Gradle Build Scan / Java ${{ matrix.java }}'
+          state: 'error'
+      - name: Update Status Check
+        if: ${{ steps.publish-build-scan.outcome == 'success' }}
+        uses: ./.github/actions/gh-api-update-status
+        with:
+          gh-token: ${{ secrets.GITHUB_TOKEN }}
+          repository: ${{ github.repository }}
+          commit_sha: ${{ github.event.workflow_run.head_sha }}
+          url: ${{ steps.publish-build-scan.outputs.build-scan-url }}
+          description: 'The build scan was successfully published'
+          context: 'Gradle Build Scan / Java ${{ matrix.java }}'
           state: 'success'
